#! /bin/sh
# based on https://github.com/hectcastro/docker-riak-cs/blob/develop/bin/riak.sh

IP_ADDRESS=$(ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1)

mkdir -p \
    /var/lib/riak-data/riak \
    /var/lib/riak-data/riak/bitcask \
    /var/lib/riak-data/riak/leveldb \
    /var/lib/riak-data/riak/ring \
    /var/lib/riak-data/log/riak

# Ensure correct ownership and permissions on volumes
chown -R riak:riak /var/lib/riak-data/riak /var/lib/riak-data/log/riak
chmod 755 /var/lib/riak-data/riak /var/lib/riak-data/log/riak

# Open file descriptor limit
ulimit -n 65536

nohup /bin/set-admin-keys.sh &

# Start Riak
exec /sbin/setuser riak "$(ls -d /usr/lib/riak/erts*)/bin/run_erl" "/tmp/riak" \
   "/var/log/riak" "exec /usr/sbin/riak console"
