#! /bin/sh
# based on https://github.com/hectcastro/docker-riak-cs/blob/develop/bin/stanchion.sh

mkdir -p \
    /var/lib/riak-data/stanchion \
    /var/lib/riak-data/log/stanchion

# Ensure correct ownership and permissions on volumes
chown -R stanchion:riak /var/lib/riak-data/stanchion /var/lib/riak-data/log/stanchion
chmod 755 /var/lib/riak-data/stanchion /var/lib/riak-data/log/stanchion

# Open file descriptor limit
ulimit -n 4096

# Start Stanchion
exec /sbin/setuser stanchion "$(ls -d /usr/lib/stanchion/erts*)/bin/run_erl" \
    "/tmp/stanchion" "/var/log/stanchion" "exec /usr/sbin/stanchion console"
